export const ADD_GRAT = "ADD_GRAT";
export const DELETE_GRAT = "DELETE_GRAT";
export const SET_CURRENT = "SET_CURRENT";

export const GET_GRATTITUDE = "GET_GRATTITUDE";
export const UPDATE_GRATTITUDE = "UPDATE_GRATTITUDE";
export const CLEAR_GRATTITUDE = "CLEAR_GRATTITUDE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const GRAT_ERROR = "GRAT_ERROR";

export const ADD_AFFIRMATION = "ADD_AFFIRMATION";
export const DELETE_AFFIRMATION = "DELETE_AFFIRMATION";
export const GET_AFFIRMATION = "GET_AFFIRMATION";
export const UPDATE_AFFIRMATION = "UPDATE_AFFIRMATION";
export const AF_ERROR = "AF_ERROR";
export const CLEAR_AFFIRMATION = "CLEAR_AFFIRMATION";
